### ISSUE TITLE
Error in boundingbox geojson polygon

### ISSUE THREAD

**Issue by mathieulavallee** [geojson/draft-geojson#100]
Chapter 4 or Page 9

I know the geojson is not complete, there is a //.. but the geometry is invalid because "A Polygon's first and last points must be equivalent."

Here is the geojson
```
{
    "type": "Feature",
    "bbox": [-180.0, -90.0, 180.0, 90.0],
    "geometry": {
        "type": "Polygon",
            "coordinates": [
                [
                    [-180.0, 10.0],
                    [20.0, 90.0],
                    [180.0, -5.0],
                    [-30.0, -90.0]
                ]
           ]
    }
    //...
}
```

it should look like 
```
{
    "type": "Feature",
    "bbox": [-180.0, -90.0, 180.0, 90.0],
    "geometry": {
        "type": "Polygon",
            "coordinates": [
                [
                    [-180.0, 10.0],
                    [20.0, 90.0],
                    [180.0, -5.0],
                    [-30.0, -90.0],
                    [-180.0, 10.0]
                ]
           ]
    }
    //...
}
```

Note: The geojson.org reference is also subject to this error

**Comment by sgillies** [comment]
@mathieulavallee Yes. The error is fixed in the draft (see https://github.com/geojson/draft-geojson/blob/master/middle.mkd) and the correction will appear in the next published version.

The old version of the spec published at geojson.org is frozen and won't be updated.
