### ISSUE TITLE
maintain history as files

### ISSUE THREAD

**Issue by dret** [geojson/draft-geojson#107]
what would people think about maintaining draft history as files? since IETF has a well-defined process of submitting and publishing drafts, i propose to archive these drafts so that there's easy access to all versions, and not just via github's commit history. https://github.com/dret/I-D/tree/master/sunset-header is as simple as i am doing it, and i think that's enough to give you an idea of what i am talking about. are people in favor of maintaining this kind of publication history? currently, it seems that there is no such thing.

**Comment by dret** [comment]
maybe, the rather difficult task to resolve #105 can serve as a demonstration that it would be nice to have specific versions (and discussion and commit threads) for each I-D version.

**Comment by martinthomson** [comment]
I think that this would be a bad idea. Tags are the correct way to ensure that you can identify a specific version.

**Comment by sgillies** [comment]
Which reminds me, I forgot to tag -06 :sweat:

**Comment by sgillies** [comment]
I tracked down f7c677066136363c17dfab29ae73e51620388336 as the one to tag draft-butler-geojson-06.
