### ISSUE TITLE
Submit draft-ietf-geojson-00

### ISSUE THREAD

**Issue by sgillies** [geojson/draft-geojson#113]
TODO:

- [x] update Appendix B

**Comment by sgillies** [comment]
Updated in 4c98e04

**Comment by sgillies** [comment]
@martinthomson @dret can you review the draft header and title? I'll publish later this morning if it is ok.

```




Geographic JSON                                                H. Butler
Internet-Draft                                                 Hobu Inc.
Intended status: Standards Track                                 M. Daly
Expires: May 16, 2016                                            Cadcorp
                                                                A. Doyle
                                                                     MIT
                                                              S. Gillies
                                                             Mapbox Inc.
                                                               T. Schaub
                                                             Planet Labs
                                                                S. Hagen

                                                       November 13, 2015


                           The GeoJSON Format
                         draft-ietf-geojson-00

Abstract

   GeoJSON is a geospatial data interchange format based on JavaScript
   Object Notation (JSON).  It defines several types of JSON objects and
   the manner in which they are combined to represent data about
   geographic features, their properties, and their spatial extents.
   This document recommends a single coordinate reference system based
   on WGS 84.  Other coordinate reference systems are not recommended.
```

**Comment by dret** [comment]
maybe it would be better to have it like this:

title: "The Geographic JSON (GeoJSON) Format"
short: "GeoJSON"

then the short title in the upper left would turn into "GeoJSON", right? i think that may make it a little easier for people to just recognize the well-known abbreviation. in that case, maybe the abstract should start like this:

"Geographic JSON (GeoJSON) is a ..."

another option would be to get rid of the "Geographic JSON" term altogether, because it really does not seem to be something that people ever use in its complete form.

**Comment by mpdaly** [comment]
+1 for getting rid of "Geographic JSON" altogether

**Comment by adoyle** [comment]
Also +1 for getting rid of "Geographic JSON" altogether

**Comment by hobu** [comment]
> Also +1 for getting rid of "Geographic JSON" altogether

:+1:

**Comment by sgillies** [comment]
"Geographic JSON" appeared there due to my fumbling with the RFC XML format. Changed to just "GeoJSON".

**Comment by sgillies** [comment]
Submitted. Will link here when I get confirmation.

**Comment by coopdanger** [comment]
Because IETF draft names follow the draft-ietf-<wgname>-<docname> format, this draft needs to be called "draft-ietf-geojson-format" or something like that. It needs one more word at the end of the name to title the document itself.

**Comment by sgillies** [comment]
@coopdanger I was hoping @martinthomson had an angle, but I am happy with "draft-ietf-geojson-format" and will make it so.

**Comment by martinthomson** [comment]
Yeah, I think that we need to accept that the tools are incapable of handling this one.  I was hoping that the secretariat would be able to step in and accept the draft, but it seems that they aren't able.  How about you submit with a new name @sgillies.

**Comment by martinthomson** [comment]
Hang on, email was sitting in my inbox from the secretariat.  Hold off on the new name for a day if you can.

**Comment by sgillies** [comment]
@martinthomson ok.

**Comment by sgillies** [comment]
Et voilà: https://datatracker.ietf.org/doc/draft-ietf-geojson/.

**Comment by tschaub** [comment]
Beautiful.
