### ISSUE TITLE
CRS

### ISSUE THREAD

**Issue by martinthomson** [geojson/draft-geojson#115]
Other IETF specifications use the URN: `urn:ogc:def:crs:EPSG::4326`.  What is the latest recommendation from the OGC on this?  Is consistency achievable?

**Comment by dr-shorthair** [comment]
OGC deprecated the urn: version in 2010, in favour of the http URI form.

**Comment by micahcochran** [comment]
Here is the [white paper for OGC URIs that deprecated URNs](https://portal.opengeospatial.org/files/?artifact_id=39467).

**Comment by sgillies** [comment]
@martinthomson right now our use of the HTTP URI `http://www.opengis.net/def/crs/OGC/1.3/CRS84` in [section 3](https://tools.ietf.org/html/draft-ietf-geojson-00#section-3) is accompanied by this reference: https://tools.ietf.org/html/draft-ietf-geojson-00#ref-OGCURL.

@dr-shorthair is that the right reference? Is @micahcochran's suggestion better?

**Comment by micahcochran** [comment]
@sgillies I was merely trying to provide a little background information, which may not be the most current or authoritative information.  I have no opinion on CRS in geojson.

**Comment by dr-shorthair** [comment]
@sgillies The section3 ref is normative. The whitepaper is part of historical record.

**Comment by adoyle** [comment]
http://www.opengis.net/def/crs/OGC/1.3/CRS84 resolves to what seems to be an error message. Taking out the 1.3 part seems a little better http://www.opengis.net/def/crs/OGC/CRS84 but I don't know enough about OGC's intent here.

**Comment by dr-shorthair** [comment]
Thanks for pointing this out @adoyle . 
OGC is in process of transferring the CRS service to be managed by Jacobs University, and obviously there are some hitches. 
I've pinged the responsible people.
