### ISSUE TITLE
Add a "Changes to pre-spec Version" Appendix

### ISSUE THREAD

**Issue by dret** [geojson/draft-geojson#125]
should we add an informal appendix summarizing the changes from the previous pre-IETF version? in particular with #114 (the new media type) it might be good to have that, so that people can easily see the differences between the media types and the specs.
http://mailarchive.ietf.org/arch/msg/media-types/n2FNMaUv_JiOzHc4SVuc314PEQA is asking for this anyway, and maybe that's a good starting point.
if people are in agreement, i can create a PR for such a section.

**Comment by dret** [comment]
if created, https://tools.ietf.org/html/draft-ietf-geojson-00#section-1.3 should link to the appendix.

**Comment by sgillies** [comment]
@dret I'm :+1: on this.
