### ISSUE TITLE
Can a FeatureCollection/GeometryCollection be empty?

### ISSUE THREAD

**Issue by martinthomson** [geojson/draft-geojson#129]
I think that they can be.  Might be worth saying.  Or not.

**Comment by dret** [comment]
On 2016-01-26 21:28, Martin Thomson wrote:
> I think that they can be. Might be worth saying. Or not.

imho, saying things like this explicitly removes any doubt, in 
particular in the absence of a formal grammar. there's a reason why 
we're even having this discussion, right?

**Comment by sgillies** [comment]
Yes, they can be empty, and I agree that spelling this out will improve the spec.

**Comment by dret** [comment]
how does #135 look?
