### ISSUE TITLE
Why is "GeometryCollection" a "Geometry" object?

### ISSUE THREAD

**Issue by dret** [geojson/draft-geojson#148]
https://tools.ietf.org/html/draft-ietf-geojson-00#section-2.1.8 describes GeometryCollection as a type of Geometry object. this seems to be a bit confusing, as it seems to be more like a FeatureCollection. what about describing it at a higher level in the section structure, making it one of the "core object types"?
a related question then is that of nested geometry collections. https://github.com/geojson/draft-geojson/issues/74 talked about this a little bit. it probably would make sense to directly say in the specification of a GeometryCollection whether nested collections are allowed, and maybe to link to the interop considerations section.

**Comment by tschaub** [comment]
A `GeometryCollection` is useful for representing the result of an operation performed on two other geometries.  For example, the intersection of two `Polygon` geometries might be a `GeometryCollection` with a `LineString` and a `Point`.

You find `GeometryCollection` in software that provides geometry operations for intersection, union, difference, etc.  For example, in PostGIS:
```
# SELECT ST_AsText(ST_Intersection('POLYGON((0 0, 0 1, 1 1, 1 0, 0 0))'::geometry, 'LINESTRING ( 0 0, 0 3, 1 1 )'::geometry));
                     st_astext                      
----------------------------------------------------
 GEOMETRYCOLLECTION(POINT(1 1),LINESTRING(0 0,0 1))
```

By allowing a `GeometryCollection` to be represented as a geometry in GeoJSON, we allow results like these to be represented.

**Comment by dret** [comment]
maybe in support of my confusion: the spec has a lot of cases where it talks about "Geometry
-and GeometryCollection objects", which aligns with what i would see as a more logical "top-level view". i've commented on that here: https://github.com/geojson/draft-geojson/commit/45814c33897b9b0aa01df93b7a00d41e966dba6b#commitcomment-16123729

**Comment by dret** [comment]
On 2016-02-16 15:09, Tim Schaub wrote:
> A |GeometryCollection| is useful for representing the result of an
> operation performed on two other geometries. For example, the
> intersection of two |Polygon| geometries might be a |GeometryCollection|
> with a |LineString| and a |Point|.
>
> You find |GeometryCollection| in software that provides geometry
> operations for intersection, union, difference, etc. For example, in
> PostGIS:
>
> |# SELECT ST_AsText(ST_Intersection('POLYGON((0 0, 0 1, 1 1, 1 0, 0
> 0))'::geometry, 'LINESTRING ( 0 0, 0 3, 1 1 )'::geometry)); st_astext
> ----------------------------------------------------
> GEOMETRYCOLLECTION(POINT(1 1),LINESTRING(0 0,0 1)) |
>
> By allowing a |GeometryCollection| to be represented as a geometry in
> GeoJSON, we allow results like these to be represented.

i am not arguing against GeometryCollection as a concept, not at all. my 
apologies if that's what my issue sounds like.

what i am arguing for is to structure the "core types" a little 
differently, and more logically (in my opinion), by saying:

- there is a feature type
- there is a featurecollection type
- there is a geometry "abstract type" (one of "Point", "MultiPoint", 
"LineString", "MultiLineString", "Polygon", "MultiPolygon")
- there is a geometrycollection type

this way the main concepts neatly line up.

this way language in numerous places can be simplified where it now 
makes special cases for "the geometrycollection geometry type", which 
sounds awkward.

in the end, it is probably a matter of taste whether you say that a 
geometrycollection is more like a geometry, or more like a collection. i 
always find myself explaining it in the latter way, because it is at 
heart a container concept.

here's what i think would be nice as a conceptual framework, and i think 
we're close, but not quite there:

FeatureCollection          +---->  GeometryCollection
                            |
  +                         |        +
  | features                |        | geometries
  v                         |        v
               geometry     |
Feature   +----------------+---->  Geometry (6 types)

  +                                  +
  | properties                       | coordinates
  v                                  v

**Comment by dret** [comment]
```
FeatureCollection          +---->  GeometryCollection
                            |
  +                         |        +
  | features                |        | geometries
  v                         |        v
               geometry     |
Feature   +----------------+---->  Geometry (6 types)

  +                                  +
  | properties                       | coordinates
  v                                  v
```

**Comment by mpdaly** [comment]
Replied by email, but it disappeared into the ether...

"We can’t normatively reference OGC Simple Features for the geometry constructs and change their semantics at the same time."

It turns out that the reference is informative, but the same principle applies.

**Comment by dret** [comment]
On 2016-02-17 11:27 , Martin Daly wrote:
> "We can’t normatively reference OGC Simple Features for the geometry
> constructs and change their semantics at the same time."
> It turns out that the reference is informative, but the same principle
> applies.

i am not at all suggesting to change the semantics. all i am trying to 
do is to frame them in a way that may be easier to grasp for people 
working with GeoJSON. if you think i am changing them, in which way?

**Comment by mpdaly** [comment]
Your diagram has "Geometry (6 types)" when there are 7. That's confusing.

**Comment by dret** [comment]
that's because it is based on the idea of separating "GeometryCollection" (it's right above the "Geometry (6 types)" label).

**Comment by mpdaly** [comment]
The point is that GC is not seperate.

**Comment by dret** [comment]
On 2016-02-17 11:37 , Martin Daly wrote:
> The point is that GC is not seperate.

you are correct. this issue is about discussing this.

**Comment by mpdaly** [comment]
Sorry, I don't have time for a circular argument. Bye.

**Comment by adoyle** [comment]
I don't see a benefit to changing the model.

**Comment by dret** [comment]
On 2016-02-17 16:23 , Allan Doyle wrote:
> I don't see a benefit to changing the model.

communities such as W3C SDW (linked from the issue) are looking at how 
GeoJSON may fit into the bigger picture. the ability to link to other 
resources plays an important role in that, when looking at web-inspired 
architectures. if GeoJSON has a well-defined place where to put those 
identifiers, it plays better in that bigger picture.

**Comment by adoyle** [comment]
I think you meant that comment to be attached to #150

**Comment by dret** [comment]
yup, sorry, i'll delete the misdirected stuff...

On 2016-02-17 16:31 , Allan Doyle wrote:
> I think you meant that comment to be attached to #150
> <https://github.com/geojson/draft-geojson/issues/150>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geojson/draft-geojson/issues/148#issuecomment-185255874>.
>

-- 
erik wilde | mailto:erik.wilde@dret.net |
            | http://dret.net/netdret    |
            | http://twitter.com/dret    |

**Comment by martinthomson** [comment]
@dret, I think that the key point here is that - as much as it seems apropos to try to somehow create a parallel between FeatureCollection and GeometryCollection - these are not in fact analogous in the way you might hope.

As much as possible, we should be relying on the existing OGC definitions, and I think that what is currently documented is correct (it's been a little while, but I was once moderately familiar with GML).

**Comment by sgillies** [comment]
"Collection" is unfortunately overloaded. I'm going to close this and follow up on my comment over at https://github.com/geojson/draft-geojson/issues/74#issuecomment-185425504.
