### ISSUE TITLE
"id" really only for "Feature" objects?

### ISSUE THREAD

**Issue by dret** [geojson/draft-geojson#150]
https://tools.ietf.org/html/draft-ietf-geojson-00#section-2.2 looks as if currently, there only is (minimal) guidance how to use "id" identifiers for feature objects. maybe having an "id" member on other object types should be mentioned as well? is there some experience with people using identifiers for non-Feature objects?

**Comment by dret** [comment]
also mentioned on the W3C SDW mailing list: http://www.w3.org/mid/56C488B1.2020808@dret.net

**Comment by adoyle** [comment]
My preference is to leave the draft as is.

**Comment by dret** [comment]
On 2016-02-17 16:10 , Allan Doyle wrote:
> My preference is to leave the draft as is.

do you see any downside to encouraging people to use "id" if they want 
to represent identifiers for non-Feature objects?

**Comment by adoyle** [comment]
Yes. There's a slippery slope of little changes to give people hints, each one making it harder to tell whether there's a substantive change or not.

**Comment by dret** [comment]
On 2016-02-17 16:26 , Allan Doyle wrote:
> Yes. There's a slippery slope of little changes to give people hints,
> each one making it harder to tell whether there's a substantive change
> or not.

could you elaborate a bit? i am not sure if you think this is a 
substantive change or not. it would just take one pattern and apply it 
to places where no such pattern existed before. having such a pattern 
helps people to decide what to use, if they want to use identifiers.

(this one was misdirected earlier. sorry.)

communities such as W3C SDW (linked from the issue) are looking at how 
GeoJSON may fit into the bigger picture. the ability to link to other 
resources plays an important role in that, when looking at web-inspired 
architectures. if GeoJSON has a well-defined place where to put those 
identifiers, it plays better in that bigger picture.

**Comment by mpdaly** [comment]
Yep: status quo please.

I thought that I might be OK with "id" at the Feature Collection level, but that could bring a whole heap of global/universal id pain, so I'd rather not.

As for Geometry, it's SFSQL again: Geometry is a property of a Feature, pulled out in its own member here because of complexity/importance/discoverability/convenience/whatever, not because of its identity.

Feature is the object with identity, Feature Collection at a push. If Geometry, just a property remember, gets identity, then logically all other properties can too, and no-one wants to see that, I trust.

**Comment by adoyle** [comment]
I mean that the more the draft gets tweaked and stretched, the further it gets a way from the 1.0 spec and the harder it is to tell whether we've changed it.

I don't see how the W3C SDW is going to be helped by non-normative wording about the use of an identifier called "id".

**Comment by dret** [comment]
On 2016-02-17 16:38 , Allan Doyle wrote:
> I mean that the more the draft gets tweaked and stretched, the further
> it gets a way from the 1.0 spec and the harder it is to tell whether
> we've changed it.

#125 should take care of that. the idea wasn't just to republish the 
original. our charter is to make changes that we (as a working group) 
think help clarify and/or improve the spec. if people want to refer to 
the original spec, they are free to do so, instead of the final RFC.

> I don't see how the W3C SDW is going to be helped by non-normative
> wording about the use of an identifier called "id".

it says SHOULD, so it has some weight and helps people to decide where 
to put their identifiers. RFC 2119:

    SHOULD: This word, or the adjective "RECOMMENDED", mean that there
    may exist valid reasons in particular circumstances to ignore a
    particular item, but the full implications must be understood and
    carefully weighed before choosing a different course.

**Comment by dret** [comment]
On 2016-02-17 16:38 , Martin Daly wrote:
> I thought that I might be OK with "id" at the Feature Collection level,
> but that could bring a whole heap of global/universal id pain, so I'd
> rather not.
> As for Geometry, it's SFSQL again: Geometry is a property of a Feature,
> pulled out in its own member here because of
> complexity/importance/discoverability/convenience/whatever, not because
> of its identity.
> Feature is the object with identity, Feature Collection at a push. If
> Geometry, just a property remember, gets identity, then logically all
> other properties can too, and no-one wants to see that, I trust.

i agree with most of this, specifically that allowing ids deeper down 
can have some granularity issues. however, i'd trust people with 
handling that reasonably, and if they don't, then it's their identity 
mess to clean up.

however, the main question is how to establish identity on the top 
level, and currently only Feature allows that. would you feel more 
comfortable to have an id as long as it's on the top level?

**Comment by mpdaly** [comment]
I'm comfortable with it as currently drafted, but would tolerate adding id at the Feature Collection level should there be consensus to do so. I do not want to see id at any other level/in any other Object.

**Comment by tschaub** [comment]
I think we should leave it as is - `id` on `Feature` only.

**Comment by tschaub** [comment]
> Yes. There's a slippery slope of little changes to give people hints, each one making it harder to tell whether there's a substantive change or not.

Agreed.

**Comment by sgillies** [comment]
The slippery slope is a logical fallacy. https://yourlogicalfallacyis.com/ has a nice summary of them that I keep on my desktop. Let's rise above these kinds of arguments! :balloon: 

@dret Feature ids give us both a way to select within a collection and a way to assert identity across collections (GIS people never do this, but web and linked data people do). Geometries, on the other hand, have no existence outside the feature that contains them. They are just a property of the feature. Features can't share them or have more than one of them, so the utility of an id seems nearly zero.

Some prose explaining the difference between features and geometries is definitely needed!

**Comment by adoyle** [comment]
I'm complaining less about this particular slippery slope than I am reacting to what seems to be a flurry of little tweaks aimed at fixing things that I don't perceive as broken.

**Comment by dret** [comment]
On 2016-02-17 23:38, Sean Gillies wrote:
> Some prose explaining the difference between features and geometries is
> definitely needed!

#149 to the rescue! i think things are nicely converging, thanks!

**Comment by dret** [comment]
there's little enthusiasm for this proposal after discussing here and on the list. closing this without action: http://mailarchive.ietf.org/arch/msg/geojson/i2vpswwCIAKkdaB_3ffrbicPbBs
