### ISSUE TITLE
Upload -02

### ISSUE THREAD

**Issue by sgillies** [geojson/draft-geojson#166]
There are nits to fix.

**Comment by sgillies** [comment]
@martinthomson @dret Just checking: we're waiting for the end of last call for upload of -02, yes?

**Comment by martinthomson** [comment]
You won't be able to push -02 until the draft submission opens up again, which happens on the 4th.  (Stupid meeting rules).  I expect that we can have a publication request in front of an area director pretty quickly after that.

**Comment by coopdanger** [comment]
I can override the meeting rules to get this published sooner if you'd like.

**Comment by sgillies** [comment]
@coopdanger works for me if it's cool with the chairs.

**Comment by sgillies** [comment]
https://tools.ietf.org/html/draft-ietf-geojson-02
