### ISSUE TITLE
Bad link in Copyright Notice

### ISSUE THREAD

**Issue by tschaub** [geojson/draft-geojson#186]
On [page 2](https://tools.ietf.org/html/draft-ietf-geojson-01#page-2) of the published draft, there is a bad link in this sentence:

> Code Components extracted from this document must
> include Simplified BSD License text as described in Section 4.e of
> the Trust Legal Provisions and are provided without warranty as
> described in the Simplified BSD License.

The link goes to [Section 4](https://tools.ietf.org/html/draft-ietf-geojson-01#section-4) of the same document.  But I assume it is either not supposed to be a link or it is supposed to go elsewhere.

I don't immediately see how this text is generated, so don't have a fix.

**Comment by martinthomson** [comment]
This isn't something we can fix here.  It's part of the automatically generated conversion from txt -> html on tools.ietf.org.  It's a common complaint, which makes me wonder why they can't fix it there.

**Comment by tschaub** [comment]
Thanks for the explanation @martinthomson.  I'll ticket elsewhere if I can find the appropriate place.
