### ISSUE TITLE
Potentially confusing language about extending GeoJSON

### ISSUE THREAD

**Issue by tschaub** [geojson/draft-geojson#187]
The section on [extending GeoJSON](https://github.com/geojson/draft-geojson/blob/f3674084ff96ac8b19ba532299e529d42de30e1e/middle.mkd#extending-geojson) describes how additional foreign members may be added to extend GeoJSON objects.  Two examples are given for extending a `Feature`.  The language in the [next paragraph](https://github.com/geojson/draft-geojson/blob/f3674084ff96ac8b19ba532299e529d42de30e1e/middle.mkd#geojson-types-are-not-extensible) feels a bit contradictory:

> Implementations MUST NOT extend ... Feature ...

I *think* what [this section](https://github.com/geojson/draft-geojson/blob/f3674084ff96ac8b19ba532299e529d42de30e1e/middle.mkd#geojson-types-are-not-extensible) is trying to communicate is that the value of the `type` member must be one of the nine [GeoJSON types](https://github.com/geojson/draft-geojson/blob/f3674084ff96ac8b19ba532299e529d42de30e1e/middle.mkd#definitions).

This same requirement is described in the section on [GeoJSON Object](https://github.com/geojson/draft-geojson/blob/f3674084ff96ac8b19ba532299e529d42de30e1e/middle.mkd#geojson-object):

> A GeoJSON object MUST have a member with the name "type". The value of the member MUST be one of the GeoJSON types.

Is the ["GeoJSON types are not extensible" paragraph](https://github.com/geojson/draft-geojson/blob/f3674084ff96ac8b19ba532299e529d42de30e1e/middle.mkd#geojson-types-are-not-extensible) just reiterating the requirement in the ["GeoJSON Object" paragraph](https://github.com/geojson/draft-geojson/blob/f3674084ff96ac8b19ba532299e529d42de30e1e/middle.mkd#geojson-object)?

If so, I wonder if it could be less open to misinterpretation.  Maybe:

> The value of the "type" member MUST be one of the fixed set of GeoJSON types: FeatureCollection, Feature, Point, LineString, MultiPoint, Polygon, MultiLineString, MultiPolygon, and GeometryCollection.

Or is there something else implied in "implementations MUST NOT extend ..."?

**Comment by sgillies** [comment]
@tschaub What I'm trying to express is that extensions can not add to the set of GeoJSON types. For example, an extension cannot add "Circle" or "GreatCircleArc" to the GeoJSON types.

It does reiterate, but also says that that the set of types is not extensible. At least that's my intent. Is there a better way to express it?

**Comment by tschaub** [comment]
@sgillies I get it (the "type" member must be one of ...).  Just thinking that someone coming to the spec wondering "Can I extend a GeoJSON Feature?" might leave uncertain ("types are not extensible" leaves room for misinterpretation).

I just re-read and it didn't bother me as much.  So if it doesn't strike anyone else as misleading, we can call this closed.
