### ISSUE TITLE
OGC CRS URL issue

### ISSUE THREAD

**Issue by tschaub** [geojson/draft-geojson#209]
In #29, it was suggested that we use http://www.opengis.net/def/crs/OGC/1.3/CRS84 instead of `urn:ogc:def:crs:OGC::CRS84` to identify a geographic coordinate system using the WGS84 datum, the prime meridian through Greenwich, and units of decimal degrees.

http://www.opengis.net/def/crs/OGC/1.3/CRS84 currently returns a 404 with this body:
```

<?xml version="1.0" encoding="ISO-8859-1"?>

<ows:ExceptionReport version="2.0.0" xsd:schemaLocation="http://www.opengis.net/ows/2.0 http://schemas.opengis.net/ows/2.0/owsExceptionReport.xsd" xmlns:ows="http://www.opengis.net/ows/2.0" xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance" xmlns:xlink="http://www.w3.org/1999/xlink">
  <ows:Exception exceptionCode="NoSuchDefinition">
    <ows:ExceptionText>Failed resolving http://www.opengis.netcrs/OGC/1.3/CRS84</ows:ExceptionText>
  </ows:Exception>
</ows:ExceptionReport>
```

I've looked through the OGC white paper 10-124r1 (https://portal.opengeospatial.org/files/?artifact_id=39467) but don't see an official position from the OGC on using this (or other) http URI.

Should we revert to the URN, use a different URL, or remove the sentence?

**Comment by sdrees** [comment]
I eould fall nack on the URN. And when the consortium offers agin abrezroevable URL this stands then for it as URNs are ok for that IMO.

**Comment by percivall** [comment]
A couple people knowledgeable about the OGC URL have nearly concluded a discussion.  I'm encouraging them to respond.  My sense is that its too soon to revert to URN.

**Comment by sgillies** [comment]
I'm in favor of reverting to the URN and not waiting for an external discussion to finish. The URN does identify the coordinate systems we discuss in the draft and since these identifiers aren't actually used in GeoJSON data I don't see harm in switching back to the URN.
