### ISSUE TITLE
Confusion about uncertainty

### ISSUE THREAD

**Issue by tschaub** [geojson/draft-geojson#211]
In an [April 12 email](http://www.ietf.org/mail-archive/web/geojson/current/msg00326.html), Alissa Cooper wrote in with this comment:

> The other geographic position formats that have been specified previously in the IETF include some support for expressing uncertainty. It would be helpful to explain somewhere in this spec why it is not doing that.

In response, @sgillies proposed #198.  There was some question there about the language in the PIDF-LO example given (see https://github.com/geojson/draft-geojson/pull/198#discussion_r60155020 on "may" versus "MAY" or "might").

In a [June 1 email](https://www.ietf.org/mail-archive/web/gen-art/current/msg13345.html), Meral Shirazipour wrote in with this comment:

> it says "Applications such as PIDF-LO that are sensitive to location uncertainty and confidence might treat ..."
> Not clear: if this is not an OK behavior, it should say "should not treat..."? If this is an ok behavior, maybe it should say "MAY treat ..."

So the additional language on uncertainty has generated some confusion.

I think we have agreement on this part:

> As in [RFC5870] the number of digits of the values in coordinate positions MUST NOT be interpreted as an indication to the level of uncertainty.

I wonder if this would be enough to address the original comment.

The part about recommending that a polygon be used to represent a 95% confidence surface for a point in PIDF-LO applications feels oddly specific to me.

**Comment by sgillies** [comment]
> The part about recommending that a polygon be used to represent a 95% confidence surface for a point in PIDF-LO applications feels oddly specific to me.

I know what you mean about oddly specific @tschaub. I feel like it's useful to the GIS community to introduce uncertainty and make a bridge to the discussion in RFC 7459, but a little more context is needed to do that.

**Comment by tschaub** [comment]
@sgillies with @coopdanger's comment on #212 (see https://github.com/geojson/draft-geojson/pull/212#issuecomment-224747095), I merged that in.  That leaves us with the minimal language on uncertainty to address the [original concern](http://www.ietf.org/mail-archive/web/geojson/current/msg00326.html).  If you'd like to come up with additional language about how uncertainty surfaces could be represented, I think that could be a separate effort.
