### ISSUE TITLE
Upload -04

### ISSUE THREAD

**Issue by sgillies** [geojson/draft-geojson#222]
After resolving the other issues in the -04 milestone.

**Comment by sgillies** [comment]
PRs resolving the last issues:

- [ ] #224 
- [ ] #225 
- [ ] #226 
- [ ] #227 
- [ ] #228 
- [ ] #229 
- [ ] #230

**Comment by mpdaly** [comment]
These work for me, save for a comment on #226

**Comment by sgillies** [comment]
Done!

**Comment by dret** [comment]
congrats!
