### ISSUE TITLE
Suggested non-substantive wording improvements

### ISSUE THREAD

**Issue by stevage** [geojson/draft-geojson#234]
I was having a closer read of the spec (while making https://geojson.win) and noticed a few areas where the wording is inconsistent, confusing or contradictory. I have no idea if there's any scope to improve any of this stuff, but...here you go. In reading this, please insert "IMHO" at the start of each line (I removed it for brevity).

If there is a mechanism for actually actioning any of this, I'm happy to be directed there.

§3. "or collection of Features" should be "or FeatureCollection".

§3. "A GeoJSON object represents a" is confusing and misleading, and should be "Every GeoJSON object is either a"

§3. Reading this section literally, one can easily believe that the minum requirement for a GeoJSON object is that it must be a JSON object with at least the `type` member. In other words `{ "type": "Geometry" }` would qualify. An additional bullet point seems justified: 'Additional requirementss apply, depending on the value of the "type" member.'

There are several places where the wording 'has a member with the name "X"' is used instead of 'has a "X" member'. Suggest replacing them all for consistency.

§3. For consistency, replace: 

> A GeoJSON object has a member with the name "type". The value of the member MUST be one of the GeoJSON types."

with

> A GeoJSON object MUST have a "type" member, the value of which MUST be one of the GeoJSON types.

There are many places where the wording "has a member" should be "MUST have a member", such as in 3, 3.1, 3.1.8, 3.2, and 3.3. 

There are many places where the wording 'the "X" member is' should be 'the "X" member MUST be'.

There are several places where "GeoJSON Geometry object" should be replaced with "Geometry object".

The relationship between "GeoJSON object", "Geometry" and "Feature" is surprisingly hard to discern, and not really spelt out clearly where you would expect, at the start of 3. I'd suggest adding additional points. With a bit of rewording, this opening paragraph could be:

>Every GeoJSON object MUST be either a Feature, a FeatureCollection, or one of the 7 Geometry object types (including GeometryCollection).
>
>*   A GeoJSON object is a JSON object.
>*   A GeoJSON object MUST have a "type", whose value MUST be one of the GeoJSON types and defines which GeoJSON object it is.
>*    Each object type defines additional requirements. For example, a Feature object MUST contain a Geometry and an additional properties object (see Section 3.2).
>*    A GeoJSON object MAY have a "bbox" member, the value of which MUST be a bounding box array (see Section 5).
>*    A GeoJSON object MAY have other members (see Section 6).

§3.1.9 "In representing Features that..." is confusingly introduced before Features are, and is not in any case specific to Features. Suggest removing this sentence, and replacing "geometry" in the next with "Geometry".

§5.2 A similar error happens here, using "Feature" and "FeatureCollection" when the same would apply to Geometry and GeometryCollection.

§6.1 "GeoJSON semantics do not apply to foreign members and their descendants, regardless of their names and values. " seems to directly contradict 3.1 "Every Geometry object is a GeoJSON object no matter where it occurs in a GeoJSON text. " and similar in 3.2. (I don't understand the intent of these latter statements. It's not true of a Geometry object on a `properties` object, it's not true of a Geometry object on a Geometry object. It's generally not true.)

§7.1 

>The GeoJSON "coordinates" and "geometries" members define Geometry objects

This (and the two similar sentences) are confusing. Geometry objects are defined by their "type" members, not by their "coordinates" and "geometries" objects (which are additional requirements, they're not what make a Point object a Point object). I suggest removing this entire section (except first sentence, which could maybe be moved into previous section) and putting the specific "MUST NOT" sections in the relevant sections: 3.1, 3.2 and 3.3.

§A.1, §3.1.1. Although section 4 says that all coordinates must be lat/longs, there are two references to eastings/northings here.

**Comment by sgillies** [comment]
@stevage will you please read https://github.com/geojson/draft-geojson/blob/master/CONTRIBUTING.md? The mailing list is where we discuss the merits of the spec and GitHub is for pull requests and actionable items. Your ticket here is not actionable for two reasons: 1) the working group is currently closed and would need to be rechartered and restarted to revise the specification, and 2) it's a long list of items and tackling them all at once isn't tractable.
