### ISSUE TITLE
Document best practice for polar bounding boxes

### ISSUE THREAD

**Issue by sgillies** [geojson/draft-geojson#47]
Anyone want to take a stab at documenting how to represent the bounding box of Antarctica in GeoJSON? @pramsey?

I'm finding http://www.jasondavies.com/maps/bounds/ to be a cool resource for thinking about this.

**Comment by dirkx** [comment]
While hard; and assuming you do not want to introduce CRS variants; you could at the very least define that any such closed surface is to be the *minimal* surface within the used projection; and thus leverage the current right-hand ordering rule already defined (current spec says that the last and first coordinate MUST be the same - and must both be present for it to be a ring.

**Comment by sgillies** [comment]
@dirkx I'm all in favor of using minimal as a guide. To help implementers we could document heuristics for determining the smaller of the possible shapes. I'm pretty sure we'd never have to compute the areas explicitly.

**Comment by martinthomson** [comment]
I think that as long as you can do this, we're fine:

```js
function isInside(lng, lat, box) {
  return lat >= box.min.lat && lat <= box.max.lat &&
     lng >= box.min.lng && lng <= box.max.lng;
}
```

That means that polar isn't interesting, the 180th meridian is the only problem.  You could make this code more complex and insist on boxes having < 180 degrees of longitude, but that's tough.

**Comment by martinthomson** [comment]
Hmm, I just noticed that the examples imply the latter interpretation where 170, -170 crosses the date line.  That needs to be made a lot clearer.

**Comment by dirkx** [comment]
On 27 Jan 2016, at 03:40, Martin Thomson <notifications@github.com> wrote:
> 
> I think that as long as you can do this, we're fine:
> 
> function isInside(lng, lat, box
> ) {
> return lat >= box.min.lat && lat <= box.max.lat &&
>      lng  >= box.min.lng && lng <= box.max.lng
> ;
> }
> 
> That means that polar isn't interesting, the 180th meridian is the only problem. You could make this code more complex and insist on boxes having < 180 degrees of longitude, but that's tough.

I would make really clear (in normative) examples that you want:

		175 .. -175
v.s
		-175 .. 175

to mean either a 10 degree box over the ‘date’ line; or a 170 degree box with a small slice missing at the date line.

And perhaps clarify while you are on this that the lines of this bounding box are a pure 2D space _in_ the coordinate system of the geoid — i.e. for:

	box.min.lat = 30, box.max.lat = 10
	box.min.lon = 10, box.max.lat = 20

we are talking about the line where for every coordinate we have:

	t = 0 … 1
	lat(t) = 30 - t * 20
	lon(t) = 10 + t * 10;

and not things like the line of a ‘string’ hung between 30,10 .. 10,20 or the shortest distance in some other non flat 2D space.
	
Dw.

**Comment by dirkx** [comment]
On 18 Feb 2016, at 06:27, Sean Gillies <notifications@github.com> wrote:

> Closed #47 <https://github.com/geojson/draft-geojson/issues/47> via #146 <https://github.com/geojson/draft-geojson/pull/146>

Very nice - especially in combination with the dateline/antemeridian section above it*.

Should it say somewhere, e.g. near line 360 and the CSR84 point that any LINE between two points is a straight line in CSR84; i.e. can be expressed as F(lon,lat) = lon0 + (lon1 - lon0) *t ,  lat0 + (lat1-lat0) * t) for t = 0..1.

Dw.

*:   "bbox": [-120.0, -10, 120.0, +10.0]
vs.
     "bbox": [ 120.0, -10, -120.0, +10.0]

**Comment by sgillies** [comment]
Thanks, @dirkx. Bounding boxes do imply a shape and I haven't described the details of these shapes. The edges of the shapes are effectively segments of great circles because they track lines of latitude and longitude. Your expression will help.

**Comment by dirkx** [comment]
> On 18 Feb 2016, at 16:51, Sean Gillies <notifications@github.com> wrote:
> 
> Thanks, @dirkx. Bounding boxes do imply a shape and I haven't described the details of these shapes. The edges of the shapes are effectively segments of great circles because they track lines of latitude and longitude. Your expression will help.

Just did:

	https://github.com/geojson/draft-geojson/pull/154
	Minor tweak to explain carthesian lines. #154

Dw

**Comment by dirkx** [comment]
Just put in https://github.com/geojson/draft-geojson/pull/154 as a draft.
