### ISSUE TITLE
Add grammar to the spec

### ISSUE THREAD

**Issue by sgillies** [geojson/draft-geojson#55]
@sdrees wrote in the original readme

>* What about an ANTLR4 grammar as non-normative appendix B after the examples and before the contributors (which then would become Appendix C)?
* Surely no (A)BNF as GeoJSON is simply not describable through ABNF (case sensitivity is missing from literals in ABNF :-) ! ... right?

Clearly IETF members appreciate a formal grammar.

**Comment by sdrees** [comment]
The [OData TC of OASIS](https://www.oasis-open.org/committees/tc_home.php?wg_abbrev=odata) has made very good progress in adding the JSON format to the last (until now XML only) sweet spot of its Core definition, namely the Conceptual Schema Definition Language (CSDL). This is documented in the [JSON Format for CSDL Version 4.0](https://www.oasis-open.org/committees/document.php?document_id=54529&wg_abbrev=odata) draft(s).
It would be very nice, if we could find a way and perform the first steps, to help the members of OData to find the best JSON Schema approach for describing the GeoJSON elements, which are referenced by that upcoming Standard family (Version 4.0 without the JSON Format for CSDL has entered ISO process, but maintenance of OData will be exclusively performed by OASIS OData TC).
Good idea? Hope so ... Volunteers, Supporters, additional ideas warmly welcome.

**Comment by sdrees** [comment]
Maybe I should take a look myself ;-) :+1:  how one could use JSON Schema to describe GeoJSON types and thus help people out there, that mix-in GeoJSON into their specifications to support discovery and general usability of services partially based on these types. OData will be based on that schema dialect and others may follow, thus it might be not a question if, but how many schema languages we will support. I remember using DocBook via DTD and also extending via RelaxNG … but in any case I would love to offer practical answers to other communities when it comes to their needs describing what we offer.

**Comment by dret** [comment]
my 2¢ on this would be to delay a formal grammar until the need and consensus on what schema language to use clearly emerge. the problem with all formal grammars is that no matter how sophisticated they are, they only cover a subset of the actual language definition. so it usually pays off to first document the language, then wait for a clear and well-defined need for a formal language to exist, and them embark on the non-trivial challenge to formalize the language in the best available language for that need.

**Comment by sgillies** [comment]
@dret Agreed. Let's save this as work for the WG and close this issue up for now.

**Comment by dret** [comment]
fine with me, thanks!
