### ISSUE TITLE
can position "extensions" be non-number values?

### ISSUE THREAD

**Issue by dret** [geojson/draft-geojson#57]
the spec currently says the following about values in positions past the three specified elements of long, lat, and elevation:

> Additional position elements MAY be included but MUST follow the three specified above and MAY be ignored by software. Interpretation and meaning of additional elements is beyond the scope of this specification.

this seems to allow non-number values. but then again, the text about positions in general says it's "an array of numbers". so the question is: can i have non-number values past the third position? specifically, i am wondering if the following is legal position or not:
```
        [
          -122.45698875747621,
          37.78691156767309,
          138.1999969482422, 
          NULL
        ]
```
it would be good to clarify the language so that it's clear whether non-number values are allowed or not.

**Comment by sgillies** [comment]
@dret rightly or wrongly the spec says "A position is represented by an array of numbers." It's possible and maybe likely that there are programs out there that would break if they encountered strings in a position. For what it's worth, it doesn't look like Leaflet would break: https://github.com/Leaflet/Leaflet/blob/4c0f02879470cb4c1781db1739138d286040f0b4/src/layer/GeoJSON.js#L120-L122.

**Comment by dret** [comment]
@sgillies you're definitely correct that the spec currently says "an array of numbers". so as the simplest possible clarification, i would suggest to add some text that any additional position elements following the initial three numbers MUST be numbers as well. i know that i am little obsessed with making extension models clear and explicit, but experience shows that this helps developers a lot.

**Comment by sgillies** [comment]
I'm still not in favor of extending the coordinates like this. It turns the GeoJSON format into a hydra of sorts, with attributes of things in several places (coordinates or properties) and different meanings for multipart geometries. But I do want things to be as clear as possible.

**Comment by jyutzler** [comment]
@dret 
Why pollute the coordinates array when you could just as easily put the timestamps on some other property? It seems that your intention is to do something that would only work within a specific community of interest. Just define a profile for your community that basically says "in addition to everything in the GeoJSON spec, we'll do these things..."

**Comment by dret** [comment]
@sgillies all i am doing is trying to use GeoJSON in a way that is in line with how GeoJSON defines extensibility. you might not like https://github.com/dret/GeoJSON-X and that's perfectly fine (i am still on the fence about this myself, it's just an experiment so far). but that's different from better documenting what GeoJSON does and does not allow.
@jyutzler i am not quite sure why using GeoJSON extensions would be "polluting" anything.  https://github.com/dret/GeoJSON-X is where i am documenting this. all i am doing here is trying to clarify how to cleanly and clearly document the way how such extensions can be defined.

**Comment by jyutzler** [comment]
@dret All I'm saying is that you're putting something other than coordinates in a property called `coordinates` and that there is no good reason to do this. You can easily do this another way, a way that could not possibly conflict with the existing specification.

**Comment by adoyle** [comment]
I agree that clarifying anything in GeoJSON that's not clear is generally good, to the extent that the clarifications don't raise additional questions and don't specifically favor any particular extension over another.

I guess we're circling back around to the "Values along a line in GeoJSON" [1], the "Data Series Proposal" [2], "Interpretation of 'extra' coordinate dimensions' [3]

[3] may be the most exhaustive discussion.

	Allan


[1] http://lists.geojson.org/htdig.cgi/geojson-geojson.org/2013-August/000821.html <http://lists.geojson.org/htdig.cgi/geojson-geojson.org/2013-August/000821.html>
[2] https://github.com/geojson/geojson-spec/wiki/Data-Series-Proposal <https://github.com/geojson/geojson-spec/wiki/Data-Series-Proposal>
[3] http://lists.geojson.org/pipermail/geojson-geojson.org/2011-August/003412.html <http://lists.geojson.org/pipermail/geojson-geojson.org/2011-August/003412.html>

**Comment by dret** [comment]
@jyutzler what GeoJSON-X does is not conflicting, at least as long as it's just using numbers. this issue here was simply about clarifying the GeoJSON part that says what is and isn't allowed.

**Comment by dret** [comment]
@adoyle i'd also be more than happy to submit pull requests for the draft. my main concern is to improve clarity and reduce ambiguity in cases where i thought that the draft language could be a bit easier to read and clearer in saying what is and isn't allowed.

**Comment by neothemachine** [comment]
A related question: Can the third position element (altitude) be null? Sometimes it is just unknown but you still want an additional dimension like time. Putting 0.0 in it would be semantically incorrect.

**Comment by dret** [comment]
@neothemachine given the current language the altitude cannot be null, which means that if you have no altitude values, you cannot add anything ("A position is represented by an array of numbers. There must be at least two elements, and may be more."). i think is unfortunate and probably just an oversight in being more well-defined and open to extensions. on the other hand, fixing this would introduce a breaking change (existing implementations only expect numbers), so this should be considered carefully.

**Comment by dret** [comment]
i think @sgillies' latest proposal was to disallow anything with more than four numbers. to my mind, then it would still be good to explain why, and how (even if the answer is "it's impossible") to handle missing elevation values. also, such a change would be backwards-incompatible (but maybe not in a way that would break a lot of what's actually out there).

**Comment by sgillies** [comment]
I've taken this to the list.

**Comment by dret** [comment]
On 2015-12-02 01:57, Sean Gillies wrote:
> I've taken this to the list.

i am fine with the proposal made at 
http://mailarchive.ietf.org/arch/msg/geojson/wfb6Nd0nEHW70EfZmdtvfC0stfQ, and 
this would resolve this issue.

it was one of the issues where i thought that answering obvious 
questions ("can i add non-number values?" "how do i add values if i do 
not have elevation values?") was harder than it should be. i am 
proposing to take this to the extensibility section as well, if the 
ability remains to add number values. then the section should also 
explicitly say that those numbers only can be added if elevation values 
are present.

if the extensibility point gets removed, then this means a breaking 
change (something that previously was valid GeoJSON now isn't anymore). 
i am fine with this as well, if there's consensus to go this way.

speaking in terms of the spec giving implementation guidance: if the 
spec says that there can be extensions, then those should be reported. 
but if they are non-number values, then it seems clear that this should 
result in an error instead. if, on the other hand, the spec disallows 
extensions, then any additional values should probably be ignored 
instead of being reported.

cheers,

dret.

**Comment by dret** [comment]
I agree with the proposal, and I think “..SHOULD contain no more than 3…” is the best way to put it. 

Even my libertarian side has its limits :)

**Comment by adoyle** [comment]
Some strange github/email interaction made my comment appear to be from @dret. Note that the above comment is from me.
