### ISSUE TITLE
IETF Process

### ISSUE THREAD

**Issue by adoyle** [geojson/draft-geojson#58]
What is the process for moving into and through the IETF process? What tasks do we need to do, what are the steps, what order are they in, and what is the approximate time line?

I'd rather get the big picture settled a little bit before engaging in a lot of debate about proposals for changes to the spec, etc. because I need to know when to really pay attention.

**Comment by sgillies** [comment]
Update: I've heard nothing from the ADs. Before I give up on a RFC, I'll ask around to see if the JSON WG might be a better fit.

For now, let's keep on working on the open issues here. The impending publication of JSON Text Sequences has me interested in writing up more formal guidance for GeoJSON text sequences, too.

**Comment by jyutzler** [comment]
I'm just going to throw this out there. It isn't too late to abandon this IETF process and go back to OGC. The first IETF draft was posted a little over a year ago and there is no end in sight. Criticize OGC all you want but the GeoPackage SWG was formed in October 2012 and the spec was adopted in February 2014. Given that GeoJSON is already feature complete and has already gone through significant review, I suspect OGC could get GeoJSON approved in about six months. I also believe there are enough members like @dr-shorthair and myself to block any unfriendly amendments to the specification. 

As someone more concerned with when the specification is adopted than who does the adopting, I encourage you to consider this path.

**Comment by sgillies** [comment]
Good news: we're moving thanks to expert and timely prodding by @dret!

**Comment by dret** [comment]
thanks a lot to all fellow prodders involved and let's keep up the momentum!
