### ISSUE TITLE
Extensions - general philosophy

### ISSUE THREAD

**Issue by adoyle** [geojson/draft-geojson#59]
Not sure when to raise this, but what the heck. The debate on RFC 5988 webby extensions vs. JSON-LD semwebby extensions in #56 makes me wonder about extensions in general. It strikes me that the beauty of extension mechanisms in JSON is that there are so many to choose from. Why do we need to specify an extension mechanism at all? Won't the communities doing the extension want to choose the mechanism that is best suited for their community? People can develop extensions any way they want, and can happily use them without us needing to include the entry points in the base spec. Look at https://github.com/topojson/topojson-specification - they just went about their business and have what seems to be a pretty robust GeoJSON. No fuss, no muss.

**Comment by sgillies** [comment]
There are developments on the extension front. 

https://github.com/mapbox/geojson-coordinate-properties extends GeoJSON with some GPX-like features.

https://github.com/yohanboniface/geocodejson-spec extends GeoJSON for geocoding.

In each case, I've recommended to the authors that they use a namespace object for extension properties. You can see the `coordinateProperties` object in https://github.com/mapbox/geojson-coordinate-properties#example and the `geocoding` object in https://github.com/yohanboniface/geocodejson-spec/pull/4/files#diff-88fee076a2bc3c3b0d4f8c13fc45e0b8R64.

**Comment by dret** [comment]
thanks for the info; very interesting and probably good input for a possible "how to extend GeoJSON" section that can list real-world examples.

**Comment by dret** [comment]
just another data point in favor of being more explicit about extension points and models: https://github.com/geojson/geojson-ld/issues/32
meaning that for something like GeoJSON-LD to be robust (to some extent), some predictability about which extensions to expect (and then how to treat them when databinding into RDF) might be helpful.

**Comment by dret** [comment]
seeing the discussion on the list (started by https://mailarchive.ietf.org/arch/msg/geojson/A0mb9ghNpf366PpVtxAEXvif8Bk), can we maybe agree as something actionable to create an extensibility section? right now there's no place readers can go to learn about this. we will have to figure out what to put there, but just judging by the sometimes passionate opinions, we might have at reached a point where we understand that extensibility matters.

**Comment by sgillies** [comment]
Extensibility section PR here: https://github.com/geojson/draft-geojson/pull/117. Comments welcome!

**Comment by dret** [comment]
since we have a proposal now (thanks @sgillies!), maybe close this one and start tracking specific issues about extensibility?

**Comment by sgillies** [comment]
:+1:
