### ISSUE TITLE
How to use position extensions without elevation

### ISSUE THREAD

**Issue by dret** [geojson/draft-geojson#60]
in positions, extensions can be used by simply adding more values after the first three ones (the question if these extensions must be numbers is a separate one and has been raised in #57). but is it possible to use extensions when there is no elevation? it's hard to imagine how, because the spec requires number values and thus NULL would not be a valid elevation. if there indeed is no way to use extensions when there is no elevation data, then maybe adding a clarification about this would be useful.

**Comment by sgillies** [comment]
@dret I don't see how to avoid elevation-extension conflict at the 3rd coordinate place. Existing programs expect a number there if anything.

**Comment by dret** [comment]
@sgillies so then let's be explicit and say that extensions MUST follow elevation values, and since NULL is not an allowed elevation value, it is impossible to use extensions when there is no elevation value.
