### ISSUE TITLE
If/How to support JSON Text Sequence serialization

### ISSUE THREAD

**Issue by dret** [geojson/draft-geojson#64]
https://datatracker.ietf.org/doc/draft-ietf-json-text-sequence/ is getting close to completion and an interesting way how potentially large collections of JSON objects can be serialized without having to wrap them in one all-encompassing JSON structure. maybe there is a way how this could fit into GeoJSON's overall picture.

**Comment by sgillies** [comment]
@dret this morning I typed up a README for the repo at https://github.com/geojson/geojson-feature-sequences as a step toward making the GeoJSON feature sequence a real thing.

**Comment by dr-shorthair** [comment]
+1 
I have always felt vaguely uncomfortable about having 'generic' containers as part of the information model (GML FeatureCollection, for example) and then implementing them literally in the technology platform, because they often do not play nice with the implementation technology, which typically has its own container anyway.

**Comment by dret** [comment]
quite a coincidence, it seems. we could consider creating a separate spec just for those, or integrating them into the current draft as an optional representation that could, for example, be nicely negotiated by using different media types for the different serialization forms.

**Comment by sgillies** [comment]
How about a different spec for starters? I have a feeling that will minimize the friction for getting draft-geojson to RFC.

**Comment by dret** [comment]
i am fine with that and would even volunteer to whip up a first draft. then we can simply see how fast the core I-D advances and how simple/contentious the "GeoJSON sequences" I-D is. if everything lines up well, we can merge them a bit further down the road. all of this of course hinges on the JSON sequences to be granted RFC-hood soon, but i think that's likely to happen.

**Comment by dret** [comment]
update: https://tools.ietf.org/html/rfc7464 is the official RFC for "JSON Text Sequences" that was published just yesterday.

**Comment by martinthomson** [comment]
@dret, @sgillies, is this something that you want to pursue separately?

**Comment by dret** [comment]
maybe another informative appendix simply talking about this and saying that this spec is not doing anything about it, but that anybody looking for having more than one GeoJSON object in one resource might consider looking at RFC 7464. we could even say that maybe there will a draft about this.

**Comment by martinthomson** [comment]
@dret, if you think that there is something to do here, or even the possibility of such, could you send an email to geojson@ietf.org with a proposal?

**Comment by dret** [comment]
done: http://mailarchive.ietf.org/arch/msg/geojson/U7Rlp9HSTKguBAQXzUBEtkAtYZw (and over and out discussing this on github :-)

**Comment by dret** [comment]
#132 has been created and should be discussed on the list.

**Comment by dret** [comment]
call to merge #132 for closing this issue: http://mailarchive.ietf.org/arch/msg/geojson/2BZDNzN1S5eRVJkmwAlikLFLUfo

**Comment by dret** [comment]
merging #132 closes this issue.
