### ISSUE TITLE
Send charter proposal to dispatch@ietf.org

### ISSUE THREAD

**Issue by sgillies** [geojson/draft-geojson#65]
Directions from the AD:

> Sorry for the delay here.  It looks like the next step here is to send a charter proposal to the DISPATCH mailing list, dispatch@ietf.org.  Then we'll have some discussion at the IETF meeting in Dallas, and assuming there are no blockers (I don't foresee any), we'll get the charter sent to the IESG.
>
> Would you mind sending your draft charter to DISPATCH?  You can crib from some of the prior examples, e.g.:
http://www.ietf.org/mail-archive/web/dispatch/current/msg05560.html

**Comment by sgillies** [comment]
- [x] charter.md updated (#66)
- [ ] mail to dispatch

**Comment by dret** [comment]
done, message sent and awaiting moderator approval. keep an eye on http://www.ietf.org/mail-archive/web/dispatch/current/maillist.html. this issue (#65) can be closed, but i cannot do it.

**Comment by tschaub** [comment]
http://www.ietf.org/mail-archive/web/dispatch/current/msg05795.html

Thanks @dret!
