### ISSUE TITLE
Update of name and email address in contact and cover sections

### ISSUE THREAD

**Issue by sdrees** [geojson/draft-geojson#68]
On friday, 13 this year the usage of the name Stefan Drees - to indicate me - will be deprecated :grinning:  After my marriage It will become Stefan Hagen instead. 
Also the email address for my contact entry will need an update, as the new email address will then be: stefan@hagen.link
I will offer a pull request, when it is done ...

**Comment by sgillies** [comment]
Congratulations, @sdrees! An auspicious day :)

**Comment by sdrees** [comment]
Hm, I can't remember the collaboration model we settled on for tiny fixes/updates like the below change:

        diff --git a/template.xml b/template.xml
        index e9ace66..e6fa4ec 100644
        --- a/template.xml
        +++ b/template.xml
        @@ -51,8 +51,8 @@
                         fullname="C. Schmidt">
                     <organization>MetaCarta</organization>
                 </author>-->
        -        <author initials="S." surname="Drees"
        -                fullname="S. Drees">
        +        <author initials="S." surname="Hagen"
        +                fullname="S. Hagen">
                     <address>
                         <postal>
                             <street>Rheinaustr. 62</street>
        @@ -63,8 +63,8 @@
                         </postal>
        
                         <phone></phone>
        -                <email>stefan@drees.name</email>
        -                <uri>http://sdre.es/</uri>
        +                <email>stefan@hagen.link</email>
        +                <uri>http://stefan-hagen.website/</uri>
                     </address>
                 </author>
                 <date day="28" month="January" year="2015"/>

Could someone advice me, if I create a branch in our repo push and then issue a pull request, or ...?

Thanks a bunch,
Stefan.

**Comment by sgillies** [comment]
@sdrees edit template.xml as directly as you want :+1:

**Comment by sdrees** [comment]
Done. Thanks.
