### ISSUE TITLE
Grant some rights to IETF trust

### ISSUE THREAD

**Issue by sgillies** [geojson/draft-geojson#70]
The IETF needs some rights to GeoJSON. The [way this works](http://www.rfc-editor.org/rfc/rfc5378.txt) is that we grant rights to the IETF Trust and the Trust then grants them to the IETF. Which rights? See [RFC 5378 sec 5.3](https://tools.ietf.org/html/rfc5378#section-5.3):

> 5.3.  Rights Granted by Contributors to the IETF Trust
>
>  To the extent that a Contribution or any portion thereof is protected
>   by copyright or other rights of authorship, the Contributor and each
>   named co-Contributor grant a perpetual, irrevocable, non-exclusive,
>   royalty-free, world-wide, sublicensable right and license to the IETF
>   Trust under all such copyrights and other rights in the Contribution:
>
>   a. to copy, publish, display, and distribute the Contribution, in
>      whole or in part,
>
>   b. to prepare translations of the Contribution into languages other
>      than English, in whole or in part, and to copy, publish, display,
>      and distribute such translations or portions thereof,
>
>   c. to modify or prepare derivative works (in addition to
>      translations) that are based on or incorporate all or part of the
>      Contribution, and to copy, publish, display, and distribute such
>      derivative works, or portions thereof unless explicitly disallowed
>      in the notices contained in a Contribution (in the form specified
>      by the Legend Instructions), and
>
>
>
>
>
>Bradner & Contreras      Best Current Practice                 [Page 10]
>
>RFC 5378                   RFC 3978-incoming               November 2008
>
>
>   d. to reproduce any trademarks, service marks, or trade names which
>      are included in the Contribution solely in connection with the
>      reproduction, distribution, or publication of the Contribution and
>      derivative works thereof as permitted by this Section 5.3,
>      provided that when reproducing Contributions, trademark and
>      service mark identifiers used in the Contribution, including TM
>      and (R), will be preserved.

My interpretation of the CC-Attribution license on the GeoJSON spec is that the rights above are already granted. Does anyone disagree?

/cc @metazool @geojson/owners @geojson/contributors

**Comment by sgillies** [comment]
Great. Rights granted.

**Comment by crschmidt** [comment]
(I missed this when it first went by.)

Technically speaking, CC-By requires anyone who uses rights like the ones granted here to do so only if the user is doing so in line with CC license, which means that they'd need to display attribution in the form preferred by the copyright holder. The IETF grant does not maintain this responsibility.

I highly doubt that any copyright holder is likely to object to granting these rights, but it's not clear to me that CC-By is actually sufficient; that said, I think given the silence of the other authors on this front, it's reasonable to grant these rights to the trust in any case.

(My reading of CC-By may be wrong here, but that's how I'd read it.)

**Comment by sgillies** [comment]
@crschmidt thank you! I'll report back as soon as I hear from Mary Barnes. It may be that attribution is a blocker. If so, I take it that you would not be opposed to waiving it for the IETF Trust?

**Comment by dret** [comment]
thanks for following-up with these issues. i hope once this is resolved, we can get to the fun part of the whole exercise!
