### ISSUE TITLE
Usage of I-JSON

### ISSUE THREAD

**Issue by dret** [geojson/draft-geojson#72]
now that I-JSON is available (http://tools.ietf.org/html/rfc7493), maybe it would make sense to refer to it and say that GeoJSON producers should produce I-JSON, but also should be prepared to process JSON that is not proper I-JSON (basically postel's law for GeoJSON, at least for the serialization level).

**Comment by adoyle** [comment]
This seems ok to me. I don’t think any GeoJSON elements are not already I-JSON. GeoJSON extensions would be expected to be treated as Must-Ignore by GeoJSON consumers that are not themselves aware of the extension.
