### ISSUE TITLE
Representing at IETF 93 in Prague 7/19-7/24

### ISSUE THREAD

**Issue by sgillies** [geojson/draft-geojson#75]
Attending [IETF 93](https://www.ietf.org/meeting/93/) will help our chartering processing enormously. Let's send a representative. Here are some possibilities, in my preferred order:

1. One of you other authors ;)
2. Me (I like Prague, but holy cow my summer is busy enough already)
3. Someone else from Mapbox to stand in for me (we have 2 engineers in Karlsruhe, Germany)

Any volunteers?

/cc @adoyle @mpdaly @tschaub @hobu @crschmidt @sdrees

**Comment by hobu** [comment]
Vacation that week already for me. I'm out.

**Comment by dret** [comment]
sorry, i'll be at the wrong side of the atlantic ocean. but yes, it would be great if we could arrange some representation at the meeting!

**Comment by sgillies** [comment]
I'm worried about losing momentum and am going. Mapbox is behind me all the way. Making travel plans now.
