### ISSUE TITLE
Clearly define and allow use projected crs in GeoJSON

### ISSUE THREAD

**Issue by stolstov** [geojson/draft-geojson#77]
Preferably, allow for short definitions, such as "EPSG" : 3857 to make it more compact. How one would transfer already projected data via GeoJSON? If it required unprojecting to WGS84, the process is lossy and often is slow for polygons/ polylines.

**Comment by sgillies** [comment]
This issue has been closed for some time. Please see https://github.com/geojson/draft-geojson/pull/40.

**Comment by stolstov** [comment]
@sgillies Thanks. Do I understand this correctly that the GeoJSON format is intended for WGS84 data? Is it not recommended for projected coordinate systems, such as web mercator?
