### ISSUE TITLE
Clearly define what is the interpretation of the line segment in geographic space. 

### ISSUE THREAD

**Issue by stolstov** [geojson/draft-geojson#78]
Clearly define what is the interpretation of the line segment in geographic space. If interoperability is important, preferably it should allow for Plate Carree like interpretation of WGS84, at least as a clear option.

**Comment by sgillies** [comment]
Currently (correct me if I'm wrong, folks) the prevailing interpretation is Euclidian. I agree that this should be spelled out very clearly in the draft.

**Comment by stolstov** [comment]
Is it Euclidian on the 2D plane where X axis is longitude and Y axis is latitude?

**Comment by sgillies** [comment]
@stolstov Sorry, I misunderstood your question. If you were to map GeoJSON as plate carrée, X would be longitude and Y latitude, sure.

**Comment by stolstov** [comment]
@sgillies I am sorry but this is still ambiguous in regards to polygon and line features that are defined in the GeoJSON. What does a line string with coordinates (0, 60) to (40, 60) represent in GeoJSON? That is, does it pass through (20, 60), or it is a geodesic, or something else?
