### ISSUE TITLE
Submit draft-butler-geojson-06

### ISSUE THREAD

**Issue by sgillies** [geojson/draft-geojson#79]
draft-butler-geojson-05 expires 2015-08-01.

**Comment by sgillies** [comment]
After merging #84 (which builds fine), I'll upload after after 2015-07-19 23:59 CEST (IETF-meeting local time). The submission form is closed atm.

**Comment by sgillies** [comment]
Hey @geojson/owners @geojson/contributors I'd appreciate :eyes: on this and a :+1: or :-1: by the end of the day. It addresses some issues and lets us keep the I-D moving. I'm totally open to revising this in the next revision.

**Comment by adoyle** [comment]
I'm going to say thumbs up, I trust your judgement. I'm not able to review anything today or tomorrow.

**Comment by tschaub** [comment]
#84 looks good to me (see https://github.com/geojson/draft-geojson/pull/84#issuecomment-122688226).  Thanks for submitting the new draft after merging that.

**Comment by mpdaly** [comment]
+1

Sterling work, @sgillies, sterling work
