### ISSUE TITLE
RDF/XML datatype for GeoJSON

### ISSUE THREAD

**Issue by andrea-perego** [geojson/draft-geojson#91]
I would like to ask your feedback on the use of GeoJSON as an RDF literal in GeoDCAT-AP, a metadata profile based on and compliant with the W3C Data Catalog Vocabulary, meant to define RDF bindings for INSPIRE / ISO 19115 metadata.

Now, the XSLT implementing the current GeoDCAT-AP specification maps the bounding box in the original ISO 19139 record to multiple encodings - namely, WKT, GML and GeoJSON - specified as RDF literals with property [`locn:geometry`](http://www.w3.org/ns/locn#locn:geometry).

To type these literals, we use the datatypes defined in GeoSPARQL for WKT and GML. However, as far as I know, there's no RDF/XML datatype for GeoJSON. So, for the moment the adopted solution is to use for this purpose the GeoJSON IANA media type.

You can find a detailed example in the XSLT documentation (Section: "Geographic bounding box"):

https://webgate.ec.europa.eu/CITnet/stash/projects/ODCKAN/repos/iso-19139-to-dcat-ap/browse/documentation/Mappings.md#mapping-bbox

Could you please provide your advise?

BTW, GeoDCAT-AP is currently available for public review until the end of August:

https://joinup.ec.europa.eu/node/144506/

Your feedback would be more than welcome!

Thanks!

**Comment by sgillies** [comment]
I've never seen a media type URI used as an RDF data type before, but sure, why not? You could also coin your own GeoJSON literal data type, right?

Closing this as it's not relevant to the I-D we're working on.
