### ISSUE TITLE
Charter Clarification

### ISSUE THREAD

**Issue by dret** [geojson/draft-geojson#92]
"This WG will work on GeoJSON mappings of 'geo' URIs, reinforcing the use of RFC 5870"

i am not sure what that means, and since it even is in the deliverables, maybe we could clarify this a bit? i am sure i could find out by poking around and of course somebody could probably explain it to me, but the charter should be easy to read and understand, and at least for me, "mappings" from URIs to media types is not a concept or a term that i am familiar with.

**Comment by martinthomson** [comment]
I think that this is saying that the WG will define what it means to encode a `geo:` URI in GeoJSON and vice-versa.  Noting that likely only a subset of GeoJSON documents can be translated to URIs, the group should take care to identify which GeoJSON documents can be translated.

**Comment by dret** [comment]
On 2015-11-17 01:56, Martin Thomson wrote:
> I think that this is saying that the WG will define what it means to
> encode a |geo:| URI in GeoJSON and vice-versa. Noting that likely only a
> subset of GeoJSON documents can be translated to URIs, the group should
> take care to identify which GeoJSON documents can be translated.

thanks for the clarification. 
https://tools.ietf.org/html/rfc5870#section-7 is where the geo: URI spec 
defines mappings to and from GML constructs. maybe we use this as a 
template?

**Comment by martinthomson** [comment]
Yeah, that is probably a good starting point.

**Comment by martinthomson** [comment]
@sgillies, does #123 address this?

**Comment by dret** [comment]
merged #123, so it seems like we have one less open issue. thanks @sgillies!
