### ISSUE TITLE
Drop all CRS ?

### ISSUE THREAD

**Issue by dirkx** [geojson/draft-geojson#94]
Relative to https://www.ietf.org/id/draft-butler-geojson-06.txt

Section 6.3 and 6.3

As the original http://geojson.org/geojson-spec.html#coordinate-reference-system-objects is dropped from the internet draft - I am not sure why these sections cannot be simplified to simply stating that any and all coordinates are to be in EPSG:4326.

Or alternatively - to introduce these - but do so wholesale and as a first class citizen (and allowing variant/attributed coordinates); with absence denoting EPSG:4326

**Comment by sgillies** [comment]
Issue taken to the list: https://mailarchive.ietf.org/arch/msg/geojson/pT0mJy1bINVKE4TLqGGnETkjNMc.

I don't see how we'll get consensus on either of the two suggestions. I prefer the first, but have failed to convince others.
