### ISSUE TITLE
Don't close the door on a certain class of extensions

### ISSUE THREAD

**Issue by sgillies** [geojson/draft-geojson#96]
Robert Sparks at https://mailarchive.ietf.org/arch/msg/dispatch/_1Hs1Qy-3F13a9hw_RUmgaCOa5w is asking that the WG charter *not preclude* GeoJSON extensions that would connect people and devices to locations.

> Since I ate some mic-line time at the DISPATCH meeting:
>
> I don't object to this charter.
>
> I reiterate that (if I understand the proposal correctly), these
could be used as part of a location object, or could become
a location object through extension.
>
> I suggest that you  consider adding text to the charter to ask
that the group consider its extension points carefully (in general
since you note that the user community is asking for guidance on
extensibility), and not _preclude_ extensions that would allow this
to become a location object unless the group determines such
extensibility would be harmful.
>
> RjS

I definitely don't want to rule out the use of GeoJSON in applications like geocoding or sensor webs or product tracking, so I'm :+1: on making the suggested addition.

/cc @geojson/contributors @geojson/owners

**Comment by dret** [comment]
this one is along the lines of #56 #57 #59, and i think that by addressing extensibility more explicitly in the I-D, it should be covered more or less by default.
the new angle here may be not just to look at how to treat extensions *within* GeoJSON, but to also be explicit about how GeoJSON is supposed to work when being embedded in a different "host language". maybe that's an interesting enough angle to have a separate section dealing with it.
