### ISSUE TITLE
Optional feature and feature collection metadata items

### ISSUE THREAD

**Issue by sgillies** [geojson/draft-geojson#99]
The https://github.com/opengeospatial/owscontext project proposes to extend GeoJSON with [Atom](https://tools.ietf.org/html/rfc4287#section-4.2)-like metadata items such as `authors`, `title`, and `updated`. This is a fine idea. This kind of information can improve many GeoJSON applications, not just OWS Context. However, I believe it is a mistake to extend GeoJSON via the `Feature.properties` object.

In Atom, `authors`, `title`, `updated` are encoded at the same level as `id`: directly under `<entry>`.

```xml
     <entry>
       <title>Atom draft-07 snapshot</title>
       <link rel="alternate" type="text/html"
        href="http://example.org/2005/04/02/atom"/>
       <link rel="enclosure" type="audio/mpeg" length="1337"
        href="http://example.org/audio/ph34r_my_podcast.mp3"/>
       <id>tag:example.org,2003:3.2397</id>
       <updated>2005-07-31T12:29:29Z</updated>
       <published>2003-12-13T08:29:29-04:00</published>
       <author>
         <name>Mark Pilgrim</name>
         <uri>http://example.org/</uri>
         <email>f8dy@example.com</email>
       </author>
       <contributor>
         <name>Sam Ruby</name>
       </contributor>
       <contributor>
         <name>Joe Gregorio</name>
       </contributor>
       <content type="xhtml" xml:lang="en"
        xml:base="http://diveintomark.org/">
         <div xmlns="http://www.w3.org/1999/xhtml">
           <p><i>[Update: The Atom draft is finished.]</i></p>
         </div>
       </content>
     </entry>
```

These metadata elements are separate from an Atom entry's `<content>`.

GeoJSON, especially as used by OWS Context, has excellent analogies to Atom: `FeatureCollection` and `<feed>`, `Feature` and `<entry>`, `Feature.properties` and `<content>`. These analogies are good. Let's embrace them, especially when building Atom-like applications with GeoJSON.

Let's make these metadata items standard, optional, features of GeoJSON. And let's pull them up out of `Feature.properties` so they get first class consideration like `Feature.id` and `Feature.geometry` and to prevent avoidable name collisions in `properties`.

See also https://github.com/opengeospatial/owscontext/issues/2.

**Comment by p3dr0** [comment]
+1
If you go ahead with those changes and I'll propose to the OWS Context SWG to take it in consideration and align both specs

**Comment by jyutzler** [comment]
+0
If you think these items would be useful (and used) outside of OWS Context documents then I agree they should be moved out of properties. In my experience "MAY" is synonymous with "WON'T" so I'm not sure the specification would be any better with these things in there. It isn't clear to me how an application would use these items outside the context (no pun intended) of OWS Context other than to display them, in which case it doesn't matter where they live.

**Comment by dr-shorthair** [comment]
@sgillies - you mention "such as authors, title, and updated". How would you select the set of 'metadata' properties to be included? This is a field with a very rich history and culture, and I would be concerned about making an arbitrary selection without some rationale.

**Comment by adoyle** [comment]
-1 for adding specific property names, even optional, for this purpose to the base GeoJSON spec. 

+1 for thinking hard about how to leverage other authorities' name spaces as we think about an extension mechanism.

**Comment by dret** [comment]
+1 for @adoyle's comment, which makes this issue just one scenario to consider for #59. afaict, if there were a well-defined extension model and a section on "How to extend GeoJSON", then this could be used by OWS Context and others to design extensions robustly.

**Comment by dret** [comment]
and for good measure, a profile identifier #97 could be used to clearly signal which extension(s) are present in some GeoJSON.

**Comment by sgillies** [comment]
I'm willing to consider this an extension and leave it out of the core. My sense (correct me if I'm wrong @p3dr0) is that the OWSContext authors didn't intend to extend GeoJSON, hence the choice of `Feature.properties.author` instead of `Feature.properties`. But I think the Atom metadata items are too useful to not be their own extension.

**Comment by adoyle** [comment]
> On Sep 17, 2015, at 11:01 AM, Sean Gillies <notifications@github.com> wrote:
> 
> I'm willing to consider this an extension and leave it out of the core. My sense (correct me if I'm wrong @p3dr0 <https://github.com/p3dr0>) is that the OWSContext authors didn't intend to extend GeoJSON, hence the choice of Feature.properties.author instead of Feature.properties. But I think the Atom metadata items are too useful to not be their own extension.
> 

I agree with the last sentence. Maybe Atom metadata items could be the canonical example of a proposed extension mechanism, and maybe they could be the first thing defined externally as an extension.
